[package]
name = "tiny_sse"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "bench"
harness = false

[dependencies]
memchr = "2.7.4"
futures-core = "0.3.31"
pin-project-lite = "0.2.15"

[dev-dependencies]
futures = "0.3.31"
tokio = { version = "1.41.1", features = ["rt", "fs", "macros"] }
serde_json = "1.0.133"
criterion = { version = "0.5.1", features = ["async_tokio"] }
eventsource-stream = "0.2.3"